version: '3'
services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./back-end
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
